name: Test

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - run: go run github.com/ysmood/golangci-lint

      - run: go test
